// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('auth', []).provider('auth', [
    function() {
      return {
        baseUrl: '',
        init: function(data) {
          return this.baseUrl = data.url.replace(/(\/)*$/i, '');
        },
        $get: function() {
          return {
            baseUrl: this.baseUrl
          };
        }
      };
    }
  ]).factory('beforeRequest', [
    '$localStorage', '$q', 'baseUrl', function($db, $q, url) {
      return {
        request: function(config) {
          var token;
          config.respondType = 'json';
          token = $db.get('token');
          if (token && config.url.indexOf(url) === 0) {
            console.log(config);
            config.headers['x-guid'] = token;
          }
          return config;
        }
      };
    }
  ]).config([
    '$httpProvider', function($httpProvider) {
      $httpProvider.defaults.useXDomain = true;
      $httpProvider.interceptors.push('beforeRequest');
    }
  ]).factory('$localStorage', [
    '$window', function($window) {
      return {
        set: function(key, value) {
          $window.localStorage[key] = JSON.stringify(value);
        },
        get: function(key) {
          return JSON.parse($window.localStorage[key] || null);
        },
        "delete": function(key) {
          $window.localStorage.removeItem(key);
        }
      };
    }
  ]).factory('baseUrl', [
    'auth', function(auth) {
      return auth.baseUrl;
    }
  ]).service('$auth', [
    '$http', 'baseUrl', function($http, url) {
      return {
        register: function(data) {
          return $http.post(url + '/register', angular.toJson(data)).success(function(response) {
            return response;
          }).error(function(response) {
            return response;
          });
        },
        verify: function(key) {
          return $http.get(url + "/verify/" + key).success(function(response) {
            return response;
          }).error(function(response) {
            return response;
          });
        },
        login: function(data) {
          return $http.post(url + "/login", angular.toJson(data)).success(function(response) {
            return response;
          }).error(function(response) {
            return response;
          });
        },
        logout: function() {
          return $http["delete"](url + "/logout").success(function(response) {
            return response;
          }).error(function(response) {
            return response;
          });
        },
        ping: function() {
          return $http.get(url + "/ping").success(function(response) {
            return response;
          }).error(function(response) {
            return response;
          });
        }
      };
    }
  ]);

}).call(this);
