// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('auth', []).provider('auth', [
    function() {
      return {
        baseUrl: '',
        init: function(data) {
          return this.baseUrl = data.url.replace(/(\/)*$/i, '');
        },
        $get: function() {
          return {
            baseUrl: this.baseUrl
          };
        }
      };
    }
  ]).factory('beforeRequest', [
    '$localStorage', '$q', 'baseUrl', function($db, $q, url) {
      return {
        request: function(config) {
          var token;
          config.respondType = 'json';
          token = $db.get('token');
          if (token && config.url.indexOf(url) === 0) {
            config.headers['Authorization'] = token;
          }
          return config;
        }
      };
    }
  ]).config([
    '$httpProvider', function($httpProvider) {
      $httpProvider.defaults.useXDomain = true;
      $httpProvider.interceptors.push('beforeRequest');
    }
  ]).factory('$localStorage', [
    '$window', function($window) {
      return {
        set: function(key, value) {
          $window.localStorage[key] = JSON.stringify(value);
        },
        get: function(key) {
          return JSON.parse($window.localStorage[key] || null);
        },
        "delete": function(key) {
          $window.localStorage.removeItem(key);
        }
      };
    }
  ]).factory('baseUrl', [
    'auth', function(auth) {
      return auth.baseUrl;
    }
  ]).service('$auth', [
    '$http', 'baseUrl', '$localStorage', function($http, url, $db) {
      return {
        register: function(data) {
          return $http.post(url + '/signup', angular.toJson(data));
        },
        verify: function(key) {
          return $http.post(url + "/verify/" + key);
        },
        recovery: function(email) {
          return $http.post(url + "/recovery", angular.toJson({
            email: email
          }));
        },
        passwd: function(data) {
          return $http.put(url + "/passwd", angular.toJson(data));
        },
        login: function(data) {
          return $http.post(url + "/authenticate", angular.toJson(data));
        },
        ping: function() {
          return $http.get(url + "/ping");
        },
        saveCredentials: function(res) {
          if (!res || !res.token) {
            return console.error('SaveCredentials', res);
          }
          return $db.set('token', res.token);
        },
        loadCredentials: function() {
          return $db.get('token');
        },
        deleteCredentials: function() {
          return $db["delete"]('token');
        }
      };
    }
  ]);

}).call(this);
